### ISSUE TITLE
BUG [trivial] relative path in shebang

### ISSUE THREAD

**Issue by johnny-diamond** [nicomda/domainipfy#1]
https://github.com/nicomda/domainipfy/blob/b558ebfd9e2799a91930147ed1bf9b7b13576f0c/domainipfy.py#L1

**Comment by nicomda** [comment]
I did it relative cause I was using venv. Already solved. Thank you! https://github.com/nicomda/domainipfy/blob/c685db979f77c266d8e184959440f65660aaca73/domainipfy.py#L1
